# Generated by Django 3.2.5 on 2022-04-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuser',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
